name: HACS

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a
        with:
          category: integration
